window.BOTELLAS = [{"n":1,"name":"Licorera zapato de taco alto","cat":"D","origin":"Italia · años 60–70","desc":"Licorera de vidrio con forma de zapato de mujer y taco dorado, pieza decorativa típica de bar. Conserva el licor original."},
{"n":2,"name":"Cointreau","cat":"L","origin":"Industria argentina · años 70","desc":"Licor triple sec de naranja de la casa de Angers, elaborado bajo licencia en la Argentina. Botella cuadrada ámbar con precinto de época."},
{"n":3,"name":"Larios Licor de Melocotón","cat":"L","origin":"España","desc":"Licor de durazno de la casa malagueña Larios, 20% vol., con la etiqueta ilustrada clásica."},
{"n":4,"name":"Ron Zacapa XO","cat":"G","origin":"Guatemala","desc":"Ron Solera Gran Reserva Especial, añejado a 2.300 m de altura y terminado en barricas de coñac. En su estuche original."},
{"n":5,"name":"Kaldí Licor de Café","cat":"L","origin":"Colombia","desc":"Licor de café de la Industria Licorera de Caldas (Manizales), en su versión para exportación. Etiqueta roja con granos de café."},
{"n":6,"name":"Limoncello Delle Piane","cat":"L","origin":"Italia","desc":"Licor italiano de limón hecho por maceración de cáscaras. Botella alta con etiqueta de estilo tradicional."},
{"n":7,"name":"Christie's London Dry Gin","cat":"G","origin":"Inglaterra · años 70","desc":"Gin inglés muy difundido en Italia en los años 70. Botella facetada con el monograma de la marca en relieve."},
{"n":8,"name":"Licorera Caballero Azul","cat":"D","origin":"Porcelana","desc":"Decantador de porcelana cobalto con filetes dorados que representa a un caballero medieval a caballo."},
{"n":9,"name":"Licorera Caballero Blanca","cat":"D","origin":"Porcelana","desc":"Versión en porcelana blanca con oro del caballero a caballo, pareja del ejemplar azul."},
{"n":10,"name":"Johnnie Walker · 150 aniversario","cat":"D","origin":"Escocia · 1970","desc":"Figura dorada del Striding Man que conmemora los 150 años de la marca (1820–1970). Pieza de exhibición para bares."},
{"n":11,"name":"Johnnie Walker Striding Man","cat":"D","origin":"Escocia · años 70","desc":"Figura publicitaria del caminante de levita roja y bastón. La base lleva el lema “Born 1820 – Still going strong”."},
{"n":12,"name":"Renault Carte Noire Extra · automóvil","cat":"D","origin":"Francia","desc":"Coñac Renault Extra Old en un decantador de porcelana con forma de automóvil antiguo, muy buscado por coleccionistas."},
{"n":13,"name":"Legend of Kremlin","cat":"G","origin":"Rusia","desc":"Vodka premium en estuche con forma de libro ilustrado con vistas del Kremlin."},
{"n":14,"name":"Estuche Milenio 1900–2000","cat":"V","origin":"Edición conmemorativa","desc":"Dos botellas de vino conmemorativas del cambio de milenio, en caja de madera con tapa."},
{"n":15,"name":"Lancers White Wine","cat":"V","origin":"Portugal","desc":"Vino blanco de J. M. da Fonseca en su famosa botella de gres verde, un clásico de las mesas de los años 70."},
{"n":16,"name":"Tilcara Pisco","cat":"G","origin":"Argentina","desc":"Aguardiente de uva con etiqueta ilustrada de motivos andinos. Botella de época."},
{"n":17,"name":"Booth's High & Dry","cat":"G","origin":"Inglaterra · años 70","desc":"London Dry Gin de Booth's, una de las destilerías más antiguas de Londres (1740). Etiqueta con el león rojo."},
{"n":18,"name":"Brandy Excelencia Larios","cat":"C","origin":"España","desc":"Brandy de la casa Larios de Málaga, con etiqueta y escudo de época."},
{"n":19,"name":"Pisco en huaco inca","cat":"D","origin":"Perú","desc":"Botella de cerámica con forma de figura precolombina, recuerdo típico del pisco peruano."},
{"n":20,"name":"Hennessy Napoléon · barril","cat":"D","origin":"Francia · años 80","desc":"Coñac Hennessy Napoléon en un barril de porcelana de Limoges con filetes dorados y canilla."},
{"n":21,"name":"Licorera Naipes","cat":"D","origin":"Venezuela","desc":"Botella cerámica en forma de cubo con naipes pintados, que también funciona como cenicero. Importada por Grey's Licores Mundial, Caracas."},
{"n":22,"name":"Cognac Napoléon · cubo cerámico","cat":"D","origin":"Francia","desc":"Coñac en envase cerámico cuadrado con etiqueta “Grands Prix”, que sirve también como cenicero."},
{"n":23,"name":"Tequila Coronita Reposado","cat":"G","origin":"México","desc":"Tequila 100% de agave, reposado, en botella de vidrio con etiqueta de estilo antiguo."},
{"n":24,"name":"Shibajiufang 20","cat":"G","origin":"China","desc":"Baijiu (aguardiente de sorgo) estilo Laobaigan de Hengshui, en botella de cerámica azul con tapa de madera."},
{"n":25,"name":"Elixir d'Anvers","cat":"L","origin":"Bélgica","desc":"Licor de hierbas creado en 1863 en Amberes por F. X. de Beukelaer con 32 plantas y especias."},
{"n":26,"name":"Hans Moser Cherry","cat":"L","origin":"Argentina · años 70","desc":"Licor crema de cereza elaborado en Florida (Buenos Aires) por Hans Moser."},
{"n":27,"name":"Beefeater 1,75 L","cat":"G","origin":"Inglaterra","desc":"Gin londinense con el guardia de la Torre de Londres. Botella importada de 1,75 litros, 47% vol."},
{"n":28,"name":"Ginebra Bols Sabor Intenso","cat":"G","origin":"Argentina","desc":"Ginebra de la línea argentina de Bols, en botella verde."},
{"n":29,"name":"Martell Cordon Noir Napoléon","cat":"C","origin":"Francia · años 80","desc":"Coñac Napoléon de Martell en botella negra mate, acompañado de su estuche."},
{"n":30,"name":"Rémy Martin V.S.O.P. 1 L","cat":"C","origin":"Francia · años 80","desc":"Coñac Fine Champagne de Rémy Martin en formato de un litro, con su estuche original."},
{"n":31,"name":"Camus Napoléon","cat":"C","origin":"Francia","desc":"Coñac “La Grande Marque” de Camus, con estuche de terciopelo bordó."},
{"n":32,"name":"Don Johny","cat":"L","origin":"Argentina","desc":"Licor seco al whisky de industria nacional, con la etiqueta violeta y el retrato del cowboy."},
{"n":33,"name":"Baron Otard V.S.O.P.","cat":"C","origin":"Francia","desc":"Coñac Fine Champagne del Château de Cognac, con el retrato del Barón Otard."},
{"n":34,"name":"Licor israelí","cat":"D","origin":"Israel","desc":"Decantador de vidrio oscuro con etiqueta dorada, de estilo similar al licor Sabra."},
{"n":35,"name":"Bols Prunelle","cat":"L","origin":"Países Bajos","desc":"Licor de ciruelas silvestres de la casa Bols, fundada en Ámsterdam en 1575. Etiqueta antigua."},
{"n":36,"name":"Tía María","cat":"L","origin":"Jamaica","desc":"Licor de café con vainilla. Botella clásica de 700 ml con la etiqueta rayada."},
{"n":37,"name":"Brandy Grande Fine Napoléon","cat":"C","origin":"España → Argentina","desc":"Brandy de Jerez envasado por A. R. Valdespino e importado a la Argentina. Sello de lacre rojo."},
{"n":38,"name":"Añejo W “Doble V”","cat":"W","origin":"Argentina","desc":"Whisky añejado 2 años, elaborado por Hiram Walker en Buenos Aires. Botella de un litro."},
{"n":39,"name":"La Gitana Manzanilla","cat":"V","origin":"España","desc":"Manzanilla de Bodegas Hidalgo, Sanlúcar de Barrameda, con la gitana pintada en la etiqueta."},
{"n":40,"name":"Tres Plumas","cat":"C","origin":"Argentina","desc":"Brandy nacional de 930 cc con el escudo de las tres plumas. Envase de época."},
{"n":41,"name":"Amadeus Liqueur","cat":"L","origin":"Austria","desc":"Licor en botella en forma de gota, con etiqueta inspirada en Mozart."},
{"n":42,"name":"Licorera Gato","cat":"D","origin":"Cerámica","desc":"Licorera figurativa de cerámica esmaltada con un gato dorado trepando por la botella."},
{"n":43,"name":"Vermouth Capizzano","cat":"V","origin":"Italia","desc":"Vermouth rosso con etiqueta roja y dorada llena de medallas."},
{"n":44,"name":"Ponche Kuba","cat":"L","origin":"Latinoamérica","desc":"Licor cremoso de huevo y ron, en su botella con relieve."},
{"n":45,"name":"Old Tradi Carta Dorada","cat":"G","origin":"Paraguay","desc":"Caña paraguaya extra fina de la Licorera Tradición, “suprema calidad”."},
{"n":46,"name":"Romate Sherry Seco","cat":"V","origin":"España","desc":"Jerez seco de Sánchez Romate Hnos., botella importada con etiqueta de época."},
{"n":47,"name":"Hidromiel Del Viejo San Marcos","cat":"L","origin":"Argentina","desc":"Bebida de miel fermentada de elaboración artesanal, en botella en forma de gota."},
{"n":48,"name":"Brandy Terry I Gran Reserva","cat":"C","origin":"España · años 70–80","desc":"Brandy de Jerez de Fernando A. de Terry en su botella negra mate."},
{"n":49,"name":"Gordon's Special Dry","cat":"G","origin":"Inglaterra · años 70","desc":"London Dry Gin 70° proof con el escudo real, en su botella verde cuadrada."},
{"n":50,"name":"Cointreau Extra Sec","cat":"L","origin":"Industria argentina","desc":"Otra versión del Cointreau argentino, con la etiqueta de Angers gastada por los años."},
{"n":51,"name":"Hidromiel Del Viejo San Marcos Dulce","cat":"L","origin":"Argentina","desc":"La versión dulce del hidromiel de San Marcos, con etiqueta en rombo roja."},
{"n":52,"name":"Schwarzer Urkönig","cat":"G","origin":"Alemania","desc":"Steinhäger con bayas de enebro negras, en su botella de gres negra."},
{"n":53,"name":"Dreher","cat":"C","origin":"Brasil","desc":"Aguardiente compuesto con jengibre (“conhaque”), botella de 900 ml."},
{"n":54,"name":"Naipes y dados promocionales","cat":"O","origin":"Varios","desc":"Conjunto de artículos de bar: juego de dados y mazos de naipes de Chivas Regal y J&B."},
{"n":55,"name":"Vacu-Vin","cat":"O","origin":"Francia","desc":"Bomba de vacío para conservar el vino abierto, en su blíster original."},
{"n":56,"name":"Vecchia Romagna Etichetta Nera","cat":"C","origin":"Italia · años 70","desc":"Brandy de Buton en su botella triangular con la máscara de Baco."},
{"n":57,"name":"Vecchia Romagna Etichetta Nera","cat":"C","origin":"Italia","desc":"Otra etapa del mismo brandy, con la cara de Baco en medallón dorado."},
{"n":58,"name":"Armagnac X.O. Demandis","cat":"C","origin":"Francia","desc":"Armagnac X.O. en botella redonda y plana, denominación de origen controlada."},
{"n":59,"name":"Clés des Ducs Napoléon","cat":"C","origin":"Francia","desc":"Armagnac en botella de vidrio tallado con sello de lacre rojo."},
{"n":60,"name":"Napoléon Brandy de France","cat":"C","origin":"Francia","desc":"Brandy francés “pure grape” con la corona imperial. La etiqueta está dañada."},
{"n":61,"name":"Cognac Gautier · boya de pescador","cat":"D","origin":"Francia · años 70","desc":"Coñac en botella esférica de vidrio con red de soga que imita una boya de pesca."},
{"n":62,"name":"Orahovac Maraska","cat":"L","origin":"Croacia","desc":"Licor de nueces verdes de Maraska (Zadar), en botella redonda y plana."},
{"n":63,"name":"Bénédictine D.O.M.","cat":"L","origin":"Francia","desc":"Licor de 27 hierbas y especias creado en Fécamp, Normandía. Botella con el sello de lacre."},
{"n":64,"name":"De Terry Camborio","cat":"V","origin":"España","desc":"Fino de Jerez de Terry, distribuido por Francesco Cinzano. Etiqueta con banda dorada."},
{"n":65,"name":"Gran Castell Castellblanch","cat":"V","origin":"España","desc":"Cava brut catalán de Castellblanch, con el escudo en relieve en el vidrio."},
{"n":66,"name":"Rosso Antico · botella de Dalí","cat":"D","origin":"Italia · años 70","desc":"Botella de vidrio blanco satinado diseñada por Salvador Dalí para el aperitivo Rosso Antico, con su firma."},
{"n":67,"name":"Mandarine Napoléon Grande Cuvée","cat":"L","origin":"Bélgica","desc":"Licor de mandarinas y coñac, receta asociada a la corte de Napoleón."},
{"n":68,"name":"Korean Ginseng Elixir","cat":"L","origin":"Corea del Sur","desc":"Licor coreano de ginseng (고려인삼주) en botella de vidrio con etiqueta bilingüe."},
{"n":69,"name":"D'Aubigny Crème de Marrons Glacés","cat":"L","origin":"Francia","desc":"Licor de castañas confitadas en botella con tapa en forma de torre de castillo."},
{"n":70,"name":"Clés des Ducs V.S.O.P.","cat":"C","origin":"Francia","desc":"Armagnac V.S.O.P. en botella tallada con rombo de sello."},
{"n":71,"name":"Ginebra Llave","cat":"G","origin":"Argentina","desc":"Ginebra de Peters Hermanos en la clásica botella verde, con escudo y bandera argentina."},
{"n":72,"name":"Ron Ocumare Añejo Especial","cat":"G","origin":"Venezuela","desc":"Ron añejo de la destilería Ocumare, línea Amazonas."},
{"n":73,"name":"Sandeman Seco Sherry","cat":"V","origin":"España","desc":"Fino seco de Sandeman con la silueta del Don de capa y sombrero."},
{"n":74,"name":"Renault Carte Noire","cat":"C","origin":"Francia · años 70","desc":"Coñac de la casa Renault, de Cognac, en su botella clásica de etiqueta negra."},
{"n":75,"name":"Romate Manzanilla La Pepa","cat":"V","origin":"España","desc":"Manzanilla de Sanlúcar de Sánchez Romate con la ilustración de “La Pepa”."},
{"n":76,"name":"Tanneur Napoléon XO · busto","cat":"D","origin":"Francia · Limoges","desc":"Coñac XO en un decantador de porcelana con el busto de Napoleón con bicornio dorado."},
{"n":77,"name":"Bell's · Boda Real 1981","cat":"D","origin":"Escocia · 1981","desc":"Campana de porcelana Wade con whisky Bell's que conmemora la boda de Carlos y Diana."},
{"n":78,"name":"Licorera Galeón","cat":"D","origin":"Vidrio","desc":"Botella de vidrio con forma de galeón, con velas y casco en relieve."},
{"n":79,"name":"Grant's Deluxe Scotch · jarra","cat":"D","origin":"Escocia","desc":"Jarra de gres esmaltado azul y crema con whisky Grant's Deluxe."},
{"n":80,"name":"Tomintoul 12 Oloroso","cat":"W","origin":"Escocia · Speyside","desc":"Single malt de 12 años con terminación en barricas de jerez oloroso."},
{"n":81,"name":"Glenmorangie The Original 10","cat":"W","origin":"Escocia · Highlands","desc":"Single malt de 10 años de Tain, destilado en los alambiques más altos de Escocia."},
{"n":82,"name":"Tomintoul 16","cat":"W","origin":"Escocia · Speyside","desc":"Single malt de 16 años, “the gentle dram”, con su estuche tubo."},
{"n":83,"name":"Tullamore D.E.W.","cat":"W","origin":"Irlanda","desc":"Whiskey irlandés blended de triple destilación."},
{"n":84,"name":"Johnnie Walker 18","cat":"W","origin":"Escocia","desc":"Blended scotch de 18 años (Ultimate), con estuche dorado."},
{"n":85,"name":"The Macallan Harmony Collection","cat":"W","origin":"Escocia · Speyside","desc":"Edición limitada de la serie Harmony, en estuche de fibras naturales."},
{"n":86,"name":"The Glenlivet Founder's Reserve","cat":"W","origin":"Escocia · Speyside","desc":"Single malt homenaje al fundador George Smith (1824), madurado en roble americano."},
{"n":87,"name":"The Glenlivet 18","cat":"W","origin":"Escocia · Speyside","desc":"Single malt de 18 años, Batch Reserve, con estuche azul."},
{"n":88,"name":"Chivas Regal Mizunara","cat":"W","origin":"Escocia","desc":"Blended scotch terminado en barricas de roble japonés mizunara."},
{"n":89,"name":"The GlenAllachie 9","cat":"W","origin":"Escocia · Speyside","desc":"Single malt de 9 años de la destilería de Billy Walker, con terminación en barrica de vino."},
{"n":90,"name":"Agavales Tequila Oro","cat":"G","origin":"México","desc":"Tequila oro de Jalisco con etiqueta amarilla de agaves."},
{"n":91,"name":"Old Pulteney Huddart","cat":"W","origin":"Escocia · Highlands","desc":"Single malt de Wick terminado en barricas que contuvieron whisky ahumado."},
{"n":92,"name":"Speyburn 15","cat":"W","origin":"Escocia · Speyside","desc":"Single malt de 15 años madurado en roble americano y español."},
{"n":93,"name":"Tomintoul Tempranillo Cask","cat":"W","origin":"Escocia · Speyside","desc":"Single malt Small Batch con terminación en barricas de vino tempranillo."},
{"n":94,"name":"Kavalan Concertmaster","cat":"W","origin":"Taiwán","desc":"Single malt taiwanés con terminación en barricas de oporto."},
{"n":95,"name":"Chivas Regal Mizunara","cat":"W","origin":"Escocia","desc":"Segundo ejemplar del blend terminado en roble japonés mizunara, con estuche."},
{"n":96,"name":"Old Pulteney 15","cat":"W","origin":"Escocia · Highlands","desc":"Single malt marítimo de 15 años de la destilería de Wick."},
{"n":97,"name":"The GlenAllachie 15","cat":"W","origin":"Escocia · Speyside","desc":"Single malt de 15 años madurado en barricas de jerez PX y oloroso."},
{"n":98,"name":"Hepburn's Choice 12","cat":"W","origin":"Escocia · Speyside","desc":"Single cask de embotellador independiente (Hunter Laing), destilado en Aultmore en 2010."},
{"n":99,"name":"Bateeiro Galician Wood","cat":"W","origin":"España · Galicia","desc":"Whisky gallego madurado en barricas de vino de la región, 43% vol."},
{"n":100,"name":"Napoléon Grand Empereur","cat":"C","origin":"Francia","desc":"Brandy francés con el escudo imperial, en botella ancha de hombros redondeados."}];
